### ISSUE TITLE
targets are not ordered in alphabetical order

### ISSUE THREAD

**Issue by jmilum** [wesabe/pfc#9]
I'm not sure what targets are ordered in, is it by creation? I think it would be better to order them by alphabetical order by tagname. this commit does that:

http://github.com/jmilum/pfc/commit/c2f5638def68477ab9db35228e580144608e70f2

**Comment by precipice** [comment]
It was intentional to have them ordered by creation so you could group related, non-alpha-sorted tags (e.g., "groceries" and "restaurant").

I personally think it's worse UI to have an addition get magically sorted; I think it would be better to either have a sort action (like clicking the tag name column at the top) or drag & drop reordering.
